Correct includes in sipXtacklib so it will compile under Fedora 10.
sipXtackLib/include/net/SipMessage.h needs to include <limits.h> as
it uses INT_MAX.  Previous versions of Fedora include <limits.h> in 
<sys/socket.h>, and as users of SipMessage.h included <sys/socket.h>
it compiled just fine.  But Fedora 10 changed <sys/socket.h> and it
no longer includes <limits.h>, so thus this change is needed under F10,
and is more correct and benign under F8 and previous.

BTW, for those who want to track this kinda thing down in the future,
this is what I did:

In F10, the compiler complains INT_MAX is undefined in 
  sipXtackLib/src/net/SipMessage.cpp.
So, on F8 (where it compiles just fine), I added the line "#define INT_MAX 42"
in SipMessage.cpp after all the #includes, and compiled it under F8.
So by re-defining INT_MAX in F8, I forced the compiler to do the work to 
tell me where it was previously defined, and what the include tree was.  Here
is the result:

../../../sipXtackLib/src/net/SipMessage.cpp:40:1: error: "INT_MAX" redefined
In file included from /usr/include/bits/socket.h:32,
                 from /usr/include/sys/socket.h:36,
                 from /usr/include/netinet/in.h:25,
                 from ../../../sipXtackLib/include/net/SipSrvLookup.h:21,
                 from ../../../sipXtackLib/include/net/SipTransaction.h:26,
                 from ../../../sipXtackLib/include/net/SipTransactionList.h:20,
                 from ../../../sipXtackLib/include/net/SipUserAgent.h:24,
                 from ../../../sipXtackLib/src/net/SipMessage.cpp:28:
/usr/lib/gcc/i386-redhat-linux/4.1.2/include/limits.h:74:1: error: this is the location of the previous definition

So (by working backwords) we can see that SipMessage.cpp included
   SipUserAgent.h, which included
   SipTransactionList.h, which included
   SipTransaction.h, which included
   SipSrvLookup.h, which included
   netinet/in.h, which included
   sys/socket.h, which included
   bits/socket.h, which included
   limits.h, which defined INT_MAX

A quick manual look at bits/socket.h on F10 shows it doesn't include limits.h
anymore, which is why this coded no longer compiles under F10.

--Woof!


git-svn-id: http://sipxecs.sipfoundry.org/rep/sipXecs/main@14463 ab1d8caa-1f67-47f1-9e81-24633a41865c